# Generated by Django 5.1.2 on 2026-07-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=True, help_text='Receive occasional email updates and newsletters.', verbose_name='email newsletter'),
        ),
    ]
