# Generated by Django 5.1.2 on 2026-07-18 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('profile_photo', models.ImageField(blank=True, help_text='Optional — falls back to your account avatar.', null=True, upload_to='profile-photos/', verbose_name='profile photo')),
                ('country_flag', models.ImageField(blank=True, null=True, upload_to='country-flags/', verbose_name='country flag')),
                ('rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='rating')),
                ('body', models.TextField(verbose_name='review')),
                ('approved', models.BooleanField(default=False, verbose_name='approved')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-created'],
            },
        ),
    ]
