# Generated by Django 4.2.7 on 2023-11-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='country_flag',
            field=models.ImageField(blank=True, null=True, upload_to='thedevu101-media/country-photos'),
        ),
    ]
