# Generated by Django 5.1.2 on 2026-07-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['order', '-created'], 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Ties fall back to newest.', verbose_name='order'),
        ),
    ]
