# Generated by Django 5.1.2 on 2024-10-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='country_flag',
            field=models.ImageField(blank=True, null=True, upload_to='country-photos/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='profile_photo',
            field=models.ImageField(default='thedevu101-media/profile-photos/user-default.png', null=True, upload_to='profile-photos/'),
        ),
    ]
