# Generated by Django 4.2.7 on 2023-11-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_review_country_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile_photo',
            field=models.ImageField(default='thedevu101-media/profile-photo/user-default.png', null=True, upload_to='thedevu101-media/profile-photo/user-default.png'),
        ),
    ]
