# Generated by Django 4.2.7 on 2023-11-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_review_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='profile_photo',
            field=models.ImageField(default='thedevu101-media/profile-photos/user-default.png', null=True, upload_to='thedevu101-media/profile-photo/user-default.png'),
        ),
    ]
