# Generated by Django 5.1.2 on 2026-07-18 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='title')),
                ('link', models.URLField(blank=True, max_length=255, verbose_name='link')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('photo', models.ImageField(upload_to='project-photos/', verbose_name='photo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ('order', '-created'),
            },
        ),
    ]
