# Generated by Django 5.1.2 on 2026-07-19 04:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('company', models.CharField(max_length=255, verbose_name='company')),
                ('company_uz', models.CharField(max_length=255, null=True, verbose_name='company')),
                ('company_ru', models.CharField(max_length=255, null=True, verbose_name='company')),
                ('company_en', models.CharField(max_length=255, null=True, verbose_name='company')),
                ('logo', models.ImageField(blank=True, help_text='Shown as a round avatar.', null=True, upload_to='job-logos/', verbose_name='logo')),
                ('responsibilities', models.TextField(help_text='What you did here — one item per line is rendered as a list.', verbose_name='responsibilities')),
                ('responsibilities_uz', models.TextField(help_text='What you did here — one item per line is rendered as a list.', null=True, verbose_name='responsibilities')),
                ('responsibilities_ru', models.TextField(help_text='What you did here — one item per line is rendered as a list.', null=True, verbose_name='responsibilities')),
                ('responsibilities_en', models.TextField(help_text='What you did here — one item per line is rendered as a list.', null=True, verbose_name='responsibilities')),
                ('start_date', models.DateField(verbose_name='worked from')),
                ('end_date', models.DateField(blank=True, help_text='Leave empty and tick “currently working here” for an ongoing job.', null=True, verbose_name='worked until')),
                ('is_current', models.BooleanField(default=False, help_text='Ongoing — the end date is treated as today when computing duration.', verbose_name='currently working here')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Ties fall back to newest start date.', verbose_name='order')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'work history',
                'ordering': ('order', '-start_date'),
            },
        ),
    ]
