# Generated by Django 4.2.7 on 2023-11-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='titile',
            new_name='title',
        ),
    ]
