# Generated by Django 4.2.11 on 2024-04-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_post_body_en_post_body_ru_post_body_uz_post_slug_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug_uz',
        ),
    ]
