# Generated by Django 4.2.11 on 2024-04-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_remove_post_slug_en_remove_post_slug_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app_main.tag'),
        ),
    ]
