# Generated by Django 4.2.7 on 2023-12-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_tag_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
