# Generated by Django 5.0.4 on 2024-04-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0011_post_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created', 'requests')},
        ),
    ]
