# Generated by Django 5.1.2 on 2026-07-18 19:01

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('name_uz', models.CharField(max_length=64, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=64, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=64, null=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=80, verbose_name='slug')),
                ('slug_uz', models.SlugField(blank=True, max_length=80, null=True, verbose_name='slug')),
                ('slug_ru', models.SlugField(blank=True, max_length=80, null=True, verbose_name='slug')),
                ('slug_en', models.SlugField(blank=True, max_length=80, null=True, verbose_name='slug')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
                ('slug_uz', models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('slug_ru', models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('slug_en', models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('excerpt', models.CharField(blank=True, help_text='Short summary shown in listings and link previews.', max_length=300, verbose_name='excerpt')),
                ('excerpt_uz', models.CharField(blank=True, help_text='Short summary shown in listings and link previews.', max_length=300, null=True, verbose_name='excerpt')),
                ('excerpt_ru', models.CharField(blank=True, help_text='Short summary shown in listings and link previews.', max_length=300, null=True, verbose_name='excerpt')),
                ('excerpt_en', models.CharField(blank=True, help_text='Short summary shown in listings and link previews.', max_length=300, null=True, verbose_name='excerpt')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='body')),
                ('body_uz', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='body')),
                ('body_ru', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='body')),
                ('body_en', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='body')),
                ('poster', models.ImageField(help_text='Shown as the preview image when the link is shared.', upload_to='%(class)s-posters/', verbose_name='poster image')),
                ('meta_description', models.CharField(blank=True, help_text='Up to 160 chars for search engines. Falls back to excerpt.', max_length=160, verbose_name='meta description')),
                ('meta_description_uz', models.CharField(blank=True, help_text='Up to 160 chars for search engines. Falls back to excerpt.', max_length=160, null=True, verbose_name='meta description')),
                ('meta_description_ru', models.CharField(blank=True, help_text='Up to 160 chars for search engines. Falls back to excerpt.', max_length=160, null=True, verbose_name='meta description')),
                ('meta_description_en', models.CharField(blank=True, help_text='Up to 160 chars for search engines. Falls back to excerpt.', max_length=160, null=True, verbose_name='meta description')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='%(class)ss', to='content.tag')),
            ],
            options={
                'verbose_name': 'news item',
                'verbose_name_plural': 'news',
                'ordering': ('-published_at', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
                ('slug_uz', models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('slug_ru', models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('slug_en', models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('excerpt', models.CharField(blank=True, help_text='Short summary shown in listings and link previews.', max_length=300, verbose_name='excerpt')),
                ('excerpt_uz', models.CharField(blank=True, help_text='Short summary shown in listings and link previews.', max_length=300, null=True, verbose_name='excerpt')),
                ('excerpt_ru', models.CharField(blank=True, help_text='Short summary shown in listings and link previews.', max_length=300, null=True, verbose_name='excerpt')),
                ('excerpt_en', models.CharField(blank=True, help_text='Short summary shown in listings and link previews.', max_length=300, null=True, verbose_name='excerpt')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='body')),
                ('body_uz', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='body')),
                ('body_ru', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='body')),
                ('body_en', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='body')),
                ('poster', models.ImageField(help_text='Shown as the preview image when the link is shared.', upload_to='%(class)s-posters/', verbose_name='poster image')),
                ('meta_description', models.CharField(blank=True, help_text='Up to 160 chars for search engines. Falls back to excerpt.', max_length=160, verbose_name='meta description')),
                ('meta_description_uz', models.CharField(blank=True, help_text='Up to 160 chars for search engines. Falls back to excerpt.', max_length=160, null=True, verbose_name='meta description')),
                ('meta_description_ru', models.CharField(blank=True, help_text='Up to 160 chars for search engines. Falls back to excerpt.', max_length=160, null=True, verbose_name='meta description')),
                ('meta_description_en', models.CharField(blank=True, help_text='Up to 160 chars for search engines. Falls back to excerpt.', max_length=160, null=True, verbose_name='meta description')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='%(class)ss', to='content.tag')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ('-published_at', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('body', models.TextField(max_length=3000, verbose_name='comment')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content.comment')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.news')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.post')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('created',),
            },
        ),
    ]
