# Generated by Django 5.1.2 on 2026-07-18 19:21

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='poster',
            field=models.ImageField(help_text='Shown as the preview image when the link is shared.', upload_to=content.models.poster_upload_to, verbose_name='poster image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ImageField(help_text='Shown as the preview image when the link is shared.', upload_to=content.models.poster_upload_to, verbose_name='poster image'),
        ),
    ]
