# Generated by Django 5.1.2 on 2026-07-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_news_poster_alter_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newsletter_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='newsletter_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
